### ISSUE TITLE
Any idea how to use it on windows?

### ISSUE THREAD

**Issue by croensch** [wbinglee/awscli-plugin-endpoint#11]
I see some interesting parts but i cannot get the pip to work.
```
C:\Program Files\Amazon\AWSCLI\runtime\python.exe
C:\Program Files\Amazon\AWSCLI\runtime\Lib\
C:\Program Files\Amazon\AWSCLI\runtime\Scripts\pip.exe
```

**Comment by wbingli** [comment]
I haven't tried on Windows, but how about `C:\Program Files\Amazon\AWSCLI\runtime\Scripts\pip.exe install awscli-plugin-endpoint`?

**Comment by croensch** [comment]
I get: `Fatal error in launcher: Unable to create process using '"c:\users\containeradministrator\appdata\local\temp\tmpmh44yj\runtime\python.exe"  "C:\Program Files\Amazon\AWSCLI\runtime\Scripts\pip.exe" install awscli-plugin-endpoint'`
I don't know why this is coming up because i have...
```
λ where python
C:\Python27\python.exe
C:\tools\neard\tools\python\python3.6.0.1\bin\python.bat
```

**Comment by wbingli** [comment]
Closing as it seems a pip issue on Windows.
