### ISSUE TITLE
support for per profile credentials

### ISSUE THREAD

**Issue by elyase** [wbinglee/awscli-plugin-endpoint#4]
thanks for the great plugin. Does this also support per endpoint credentials?

**Comment by elyase** [comment]
Just found out that it indeed supports per profile credentials. Just add:

```
[profile_name]
aws_access_key_id=your_key
aws_secret_access_key=your_secret
```

in `~/.aws/credentials`

**Comment by wbingli** [comment]
fyi, the per profile credential support is supported by standard AWS CLI. This plugin doesn't introduce new way for credential support.
